### ISSUE TITLE
Um erro na mensagem de aprovado e reprovado

### ISSUE THREAD

**Issue by MitchelMathias** [MickaelDutra/projeto_calculadora_de_medias#1]
Conserta ai ksksksk

![image](https://github.com/user-attachments/assets/0136c82a-ec67-433c-98c5-348dc2fdff9e)

**Comment by MitchelMathias** [comment]
Vou passar nunca kskksks

**Comment by MickaelDutra** [comment]
é pra decepcionar os alunos. Vou consertar, valeuu!
